import { Scheduler, SchedulerData } from "@bitnoi.se/react-scheduler";
import { Course2, Instructor, InstructorDetail, Todo } from "@/type/course";

export const Department = ["Digital Marketing", "Web Developmenr", "UX/UI"];
export const Program = ["DMA", "DMS"];

export const Cohort: {
  program: string;
  name: string;
  room: string;
  period: string;
  course: Course2[];
}[] = [
  {
    program: "DMA",
    name: "E1-0922",
    room: "facebook",
    period: "evening",
    course: [
      {
        startDate: "2022-09-25",
        endDate: "2022-10-13",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2022-10-15",
        endDate: "2022-11-03",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2022-11-06",
        endDate: "2022-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2022-11-06",
        endDate: "2022-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2022-11-27",
        endDate: "2022-12-15",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2022-12-18",
        endDate: "2023-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2023-01-02",
        endDate: "2023-01-19",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-01-22",
        endDate: "2023-02-09",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2023-02-12",
        endDate: "2023-03-22",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "E1-0923",
    room: "facebook",
    period: "evening",
    course: [
      {
        startDate: "2023-09-25",
        endDate: "2023-10-13",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-10-15",
        endDate: "2023-11-03",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-11-27",
        endDate: "2023-12-15",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "E2-0923",
    room: "youtube",
    period: "evening",
    course: [
      {
        startDate: "2023-09-25",
        endDate: "2023-10-13",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-10-15",
        endDate: "2023-11-03",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-11-27",
        endDate: "2023-12-15",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "M1-1123",
    room: "facebook",
    period: "morning",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "A1-1123",
    room: "amazon",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "A2-1124",
    room: "google",
    period: "afternoon",
    course: [
      {
        startDate: "2024-11-25",
        endDate: "2024-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-12-18",
        endDate: "2025-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2025-01-02",
        endDate: "2025-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2025-01-22",
        endDate: "2025-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2025-01-22",
        endDate: "2025-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2025-02-12",
        endDate: "2025-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2025-03-25",
        endDate: "2025-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2025-04-15",
        endDate: "2025-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2025-05-06",
        endDate: "2025-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "A2-1123",
    room: "google",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
];

export const DMSCourse = [
  {
    title: "Analytics",
    color: "gray",
  },
  {
    title: "Campaign Management",
    color: "green",
  },
  {
    title: "Design",
    color: "orange",
  },
  {
    title: "Digital Marketing 1",
    color: "purple",
  },
  {
    title: "Digital Marketing 1",
    color: "pink",
  },
  {
    title: "SEO",
    color: "blue",
  },
  {
    title: "Social Media",
    color: "blue",
  },
  {
    title: "WordPress",
    color: "green",
  },
];

export const Room = ["Facebook", "Google", "Youtube", "Amazon"];

//program
export const weekly = [
  {
    program: "DMA",
    name: "E1-0923",
    room: "facebook",
    period: "evening",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
        color: "pink",
      },
    ],
  },
  {
    program: "DMA",
    name: "E2-0923",
    room: "youtube",
    period: "morning",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
        color: "blue",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
        color: "orange",
      },
    ],
  },
  {
    program: "DMA",
    name: "M1-1123",
    room: "facebook",
    period: "morning",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
        color: "green",
      },
    ],
  },
  {
    program: "DMA",
    name: "A1-1123",
    room: "amazon",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
        color: "gray",
      },
    ],
  },
  {
    program: "DMA",
    name: "A2-1123",
    room: "google",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
        color: "purple",
      },
    ],
  },
  {
    program: "DMA",
    name: "W1-1123",
    room: "google",
    period: "weekend",
    course: [
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
        color: "purple",
      },
    ],
  },
];

//program
export const monthly: {
  program: string;
  name: string;
  room: string;
  period: string;
  course: Course2[];
}[] = [
  {
    program: "DMA",
    name: "E1-0923",
    room: "facebook",
    period: "evening",
    course: [
      {
        startDate: "2023-09-25",
        endDate: "2023-10-13",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-10-15",
        endDate: "2023-11-03",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-11-27",
        endDate: "2023-12-15",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "E2-0923",
    room: "youtube",
    period: "evening",
    course: [
      {
        startDate: "2023-09-25",
        endDate: "2023-10-13",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-10-15",
        endDate: "2023-11-03",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-11-06",
        endDate: "2023-11-24",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-11-27",
        endDate: "2023-12-15",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "M1-1123",
    room: "facebook",
    period: "morning",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "A1-1123",
    room: "amazon",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "A2-1123",
    room: "google",
    period: "afternoon",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Wed", "Thur", "Fri"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Mon", "Tue", "Wed"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
        Instructor: "Rodrigo",
      },
    ],
  },
  {
    program: "DMA",
    name: "W1-1123",
    room: "google",
    period: "weekend",
    course: [
      {
        startDate: "2023-11-25",
        endDate: "2023-12-15",
        name: "Digital Martketing 1",
        Days: ["Sat", "Sun"],
        Instructor: "Mariam",
      },
      {
        startDate: "2023-12-18",
        endDate: "2024-01-01",
        name: "break",
        Days: [],
        Instructor: "",
      },
      {
        startDate: "2024-01-02",
        endDate: "2024-01-19",
        name: "Digital Martketing 2",
        Days: ["Sat", "Sun"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "WordPress",
        Days: ["Sat", "Sun"],
        Instructor: "Mariam",
      },
      {
        startDate: "2024-01-22",
        endDate: "2024-02-09",
        name: "Design",
        Days: ["Sat", "Sun"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-02-12",
        endDate: "2024-03-22",
        name: "SEO",
        Days: ["Sat", "Sun"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-03-25",
        endDate: "2024-04-12",
        name: "Analytis",
        Days: ["Sat", "Sun"],
        Instructor: "Brian",
      },
      {
        startDate: "2024-04-15",
        endDate: "2024-05-03",
        name: "Social Media",
        Days: ["Sat", "Sun"],
        Instructor: "Rodrigo",
      },
      {
        startDate: "2024-05-06",
        endDate: "2024-05-31",
        name: "Campaign Management",
        Days: ["Sat", "Sun"],
        Instructor: "Rodrigo",
      },
    ],
  },
];

export const Todos: Todo[] = [
  {
    id: "todo1",
    title: "Invite",
    dueDate: "2023-11-01",
    isCompleted: true,
  },
  {
    id: "todo2",
    title: "Class room",
    dueDate: "2023-11-01",
    isCompleted: false,
  },
];
export const AvailableInstructors: Instructor[] = [
  {
    id: "instructor1",
    firstName: "Brian",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
  },
  {
    id: "instructor1",
    firstName: "Caio",
    lastName: "Franco",
    avatar_url: "https://i.imgur.com/T2WwVfS.png",
  },
  {
    id: "instructor1",
    firstName: "Diogo",
    lastName: "",
    avatar_url: "https://i.imgur.com/LpaY82x.png",
  },
  {
    id: "instructor1",
    firstName: "Rafael",
    lastName: "",
    avatar_url: "https://i.imgur.com/Nmx0Qxo.png",
  },
];

export const unAvailableInstructors: Instructor[] = [
  {
    id: "instructor1",
    firstName: "Brian",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
  },
  {
    id: "instructor1",
    firstName: "Caio",
    lastName: "Franco",
    avatar_url: "https://i.imgur.com/T2WwVfS.png",
  },
  {
    id: "instructor1",
    firstName: "Diogo",
    lastName: "",
    avatar_url: "https://i.imgur.com/LpaY82x.png",
  },
  {
    id: "instructor1",
    firstName: "Rafael",
    lastName: "",
    avatar_url: "https://i.imgur.com/Nmx0Qxo.png",
  },
  {
    id: "instructor1",
    firstName: "Brian",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
  },
  {
    id: "instructor1",
    firstName: "Caio",
    lastName: "Franco",
    avatar_url: "https://i.imgur.com/T2WwVfS.png",
  },
  {
    id: "instructor1",
    firstName: "Diogo",
    lastName: "",
    avatar_url: "https://i.imgur.com/LpaY82x.png",
  },
  {
    id: "instructor1",
    firstName: "Rafael",
    lastName: "",
    avatar_url: "https://i.imgur.com/Nmx0Qxo.png",
  },
];

export const InstructorsDetail: InstructorDetail[] = [
  {
    id: "instructor0",
    firstName: "Ana",
    lastName: "Couto",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: true,
    hours: 20,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Morning", "Afternoon", "Evening", "Weekend"],
    course: [
      { program: "DMS", name: "Digital Marketing1", color: "gray" },
      { program: "DMS", name: "Digital Marketing2", color: "green" },
      { program: "DMS", name: "Campaign Management", color: "green" },
      { program: "DMS", name: "Social Media", color: "orange" },
      { program: "DMS", name: "Design", color: "orange" },
      { program: "DMS", name: "SEO", color: "blue" },
      { program: "DMS", name: "WordPress", color: "pink" },
      { program: "DMA", name: "Advanced Strategies", color: "blue" },
      { program: "DMA", name: "Content Creation", color: "green" },
    ],
    preference: [
      { program: "DMS", name: "Digital Marketing2", color: "green" },
      { program: "DMS", name: "SEO", color: "blue" },
      { program: "DMA", name: "Advanced Strategies", color: "blue" },
    ],
  },
  {
    id: "instructor1",
    firstName: "Ana",
    lastName: "Couto",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: true,
    hours: 20,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Morning", "Afternoon", "Evening"],
    course: [
      { program: "DMS", name: "Digital Marketing1", color: "gray" },
      { program: "DMS", name: "Digital Marketing2", color: "green" },
      { program: "DMS", name: "Campaign Management", color: "green" },
      { program: "DMS", name: "Social Media", color: "orange" },
      { program: "DMA", name: "Advanced Strategies", color: "blue" },
      { program: "DMA", name: "Content Creation", color: "green" },
    ],
    preference: [
      { program: "DMS", name: "Digital Marketing1", color: "gray" },
      { program: "DMS", name: "Digital Marketing2", color: "green" },
      { program: "DMA", name: "Advanced Strategies", color: "blue" },
      { program: "DMA", name: "Content Creation", color: "green" },
    ],
  },
  {
    id: "instructor2",
    firstName: "Brian",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: true,
    hours: 40,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Evening"],
    course: [
      { program: "DMS", name: "Digital Marketing1", color: "gray" },
      { program: "DMS", name: "Digital Marketing2", color: "green" },
      { program: "DMS", name: "Campaign Management", color: "green" },
      { program: "DMS", name: "SEO", color: "purple" },
      { program: "DMA", name: "Digital Ads", color: "pink" },
      { program: "DMA", name: "Ecommerce", color: "orange" },
    ],
    preference: [
      { program: "DMS", name: "SEO", color: "purple" },

      { program: "DMA", name: "Ecommerce", color: "orange" },
    ],
  },
  {
    id: "instructor3",
    firstName: "Diogo",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: true,
    hours: 20,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Evening"],
    course: [{ program: "DMS", name: "WordPress", color: "orange" }],
    preference: [{ program: "DMS", name: "WordPress", color: "orange" }],
  },
  {
    id: "instructor4",
    firstName: "Iman",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: true,
    hours: 10,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Evening"],
    course: [
      { program: "DMS", name: "Analytics", color: "gray" },
      { program: "DMA", name: "Automation", color: "purple" },
      { program: "DMA", name: "Advanced SEO", color: "orange" },
    ],
    preference: [
      { program: "DMA", name: "Automation", color: "purple" },
      { program: "DMA", name: "Advanced SEO", color: "orange" },
    ],
  },
  {
    id: "instructor5",
    firstName: "Aswini",
    lastName: "",
    avatar_url: "https://i.imgur.com/iHq8K8Z.jpg",
    isActive: false,
    hours: 10,
    Days: ["Mon", "Tue", "Wed", "Thur", "Fri"],
    period: ["Morning", "Afternoon", "Evening"],
    course: [{ program: "DMS", name: "Design", color: "orange" }],
    preference: [{ program: "DMS", name: "Design", color: "orange" }],
  },
];
